# GENERAL SETTINGS
SCREEN_WIDTH = 400
SCREEN_HEIGHT = 600
FRAMERATE = 30 # only relevant for display (not for RL agent)

# RACKET SETTINGS
RACKET_SPEED = 10
RACKET_WIDTH_START = SCREEN_WIDTH/2
RACKET_WIDTH_MIN = RACKET_SPEED
RACKET_WIDTH_DECREASE = 0.9

# BALL SETTINGS
BALL_YSPEED_START = 10
BALL_YSPEED_MAX = SCREEN_HEIGHT/2
BALL_YSPEED_INCREASE = 1.1
